"""initial schema

Revision ID: 2ffb38619296
Revises: 
Create Date: 2026-07-31 15:51:11.059948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ffb38619296'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('focus_score_avg', sa.Float(), nullable=True),
    sa.Column('posture_score_avg', sa.Float(), nullable=True),
    sa.Column('fatigue_level_end', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("fatigue_level_end IN ('fresh', 'normal', 'tired', 'very_tired') OR fatigue_level_end IS NULL", name='ck_sessions_fatigue_level_end'),
    sa.CheckConstraint("status IN ('active', 'completed', 'aborted')", name='ck_sessions_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera', sa.JSON(), nullable=False),
    sa.Column('llm', sa.JSON(), nullable=False),
    sa.Column('privacy', sa.JSON(), nullable=False),
    sa.Column('notifications', sa.JSON(), nullable=False),
    sa.Column('performance', sa.JSON(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_settings_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analytics_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('period_type', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('avg_focus_score', sa.Float(), nullable=True),
    sa.Column('avg_posture_score', sa.Float(), nullable=True),
    sa.Column('distraction_count', sa.Integer(), nullable=False),
    sa.Column('break_count', sa.Integer(), nullable=False),
    sa.Column('longest_break_seconds', sa.Integer(), nullable=True),
    sa.Column('best_hours', sa.JSON(), nullable=False),
    sa.Column('worst_hours', sa.JSON(), nullable=False),
    sa.Column('raw_metrics', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("period_type IN ('daily', 'weekly', 'monthly')", name='ck_analytics_period_type'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_type', 'period_start', 'session_id', name='idx_analytics_period')
    )
    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('source_module', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_events_confidence'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_session_id', 'events', ['session_id'], unique=False)
    op.create_index('idx_events_timestamp', 'events', ['timestamp'], unique=False)
    op.create_index('idx_events_type', 'events', ['type'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.CheckConstraint("format IN ('pdf', 'csv', 'json', 'png')", name='ck_reports_format'),
    sa.CheckConstraint("report_type IN ('daily', 'weekly', 'monthly', 'session')", name='ck_reports_type'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_index('idx_events_type', table_name='events')
    op.drop_index('idx_events_timestamp', table_name='events')
    op.drop_index('idx_events_session_id', table_name='events')
    op.drop_table('events')
    op.drop_table('analytics_snapshots')
    op.drop_table('settings')
    op.drop_table('sessions')
    # ### end Alembic commands ###
